In [1]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

In [35]:
# Loading the dataset
df = pd.read_csv("/content/superstore_final_dataset (1)(in).csv", encoding="latin-1")

In [36]:
# printing the 1st 5 rows of the dataset
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [37]:
df.info() # printing the summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   object
 2   Order_Date     9800 non-null   object
 3   Ship_Date      9800 non-null   object
 4   Ship_Mode      9800 non-null   object
 5   Customer_ID    9800 non-null   object
 6   Customer_Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product_ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub_Category   9800 non-null   object
 16  Product_Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [38]:
# Printing missing values:
mv = df.isnull().sum()
print(mv)

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

In [39]:
# Printing duplicate values:
print(df.duplicated().sum())

0

In [40]:
# Displaying null rows:
df[df.isnull().any(axis=1)]

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
2234,2235,CA-2018-104066,5/12/2018,10/12/2018,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5274,5275,CA-2016-162887,7/11/2016,9/11/2016,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,6/4/2017,10/4/2017,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9147,9148,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9386,9387,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,8/11/2016,12/11/2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90

In [41]:

# To convert Order_ID to int, we need to remove the country and year from it
df["Order_ID"] = df["Order_ID"].apply(lambda x: int(x.split("-")[-1]))

In [42]:
df['Order_ID'].head() # printing 1st 5 rows of Order_ID column

0    152156
1    152156
2    138688
3    108966
4    108966
Name: Order_ID, dtype: int64

In [43]:
# Converting Customer_ID to int:
df["Customer_ID"] = df["Customer_ID"].apply(lambda x: int(x.split("-")[-1]))

In [44]:
df['Customer_ID'].head() # printing 1st 5 rows of Customer_ID column

0    12520
1    12520
2    13045
3    20335
4    20335
Name: Customer_ID, dtype: int64

In [45]:
# Converting product_ID to int:
df["Product_ID"] = df["Product_ID"].apply(lambda x: int(x.split("-")[-1]))

In [46]:
df['Product_ID'].head() # printing 1st 5 rows of Product_ID column

0    10001798
1    10000454
2    10000240
3    10000577
4    10000760
Name: Product_ID, dtype: int64

In [47]:
# Drop the Postal_Code column
df.drop(columns=["Postal_Code"], inplace=True)

In [48]:
# Convert Dates to Datetime Format
df["Order_Date"] = pd.to_datetime(df["Order_Date"], dayfirst=True)
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"], dayfirst=True)

In [49]:
# Printing missing values
missing_values = df.isnull().sum()
print("\nMissing values in columns:")
print(missing_values)

Missing values in columns:
Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
dtype: int64

In [50]:
# Drop the 'Country' column
df_cleaned = df.drop(columns=["Country"],inplace=True)

In [51]:
# Removing unnecessary columns
columns_to_drop = ["Row_ID", "Order_ID", "Customer_ID", "Product_ID", "Customer_Name"]

# Removing unnecessary columns in the original dataset
df.drop(columns=columns_to_drop, inplace=True)

# Summarizing the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_Date    9800 non-null   datetime64[ns]
 1   Ship_Date     9800 non-null   datetime64[ns]
 2   Ship_Mode     9800 non-null   object
 3   Segment       9800 non-null   object
 4   City          9800 non-null   object
 5   State         9800 non-null   object
 6   Region        9800 non-null   object
 7   Category      9800 non-null   object
 8   Sub_Category  9800 non-null   object
 9   Product_Name  9800 non-null   object
 10  Sales         9800 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(8)
memory usage: 842.3+ KB

In [52]:
# Displaying the first 5 rows of the cleaned dataset
df.head()

,Order_Date,Ship_Date,Ship_Mode,Segment,City,State,Region,Category,Sub_Category,Product_Name,Sales
0,2017-11-08,2017-11-11,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2017-11-08,2017-11-11,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,2017-06-12,2017-06-16,Second Class,Corporate,Los Angeles,California,West,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,2016-10-11,2016-10-18,Standard Class,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,2016-10-11,2016-10-18,Standard Class,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [53]:
# Converting date columns to datetime format
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'], errors='coerce')

In [54]:
# Checking for duplicate rows
duplicate_rows = df.duplicated().sum()
print(duplicate_rows)

1

In [55]:
# Removing duplicate row
df = df.drop_duplicates()
dr=df.duplicated().sum()
print(dr)

0

In [56]:
# Checking for outliers in Sales
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)
IQR = Q3 - Q1

# Lower bound:
lower_bound = Q1 - 1.5 * IQR

# Upper bound:
upper_bound = Q3 + 1.5 * IQR

# Finding outliers
outliers = df[(df['Sales'] < lower_bound) | (df['Sales'] > upper_bound)]

# Standardizing categorical columns
categorical_cols = ['Ship_Mode', 'Segment', 'City', 'State', 'Region', 'Category', 'Sub_Category', 'Product_Name']
df[categorical_cols] = df[categorical_cols].apply(lambda x: x.str.strip().str.title())

# Summary of cleaning actions
len(outliers)

1145

In [57]:
# Any values below the lower bound are set to the lower bound
# Any values above the upper bound are set to the upper bound
df['Sales'] = df['Sales'].clip(lower=lower_bound, upper=upper_bound)


# Displaying summary of the 'Sales' column
df['Sales'].describe()

count    9799.000000
mean      140.791806
std       169.533857
min         0.444000
25%        17.248000
50%        54.480000
75%       210.572000
max       500.558000
Name: Sales, dtype: float64

In [58]:
df.head() # Printing 1st 5 rows of dataframe

,Order_Date,Ship_Date,Ship_Mode,Segment,City,State,Region,Category,Sub_Category,Product_Name,Sales
0,2017-11-08,2017-11-11,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960
1,2017-11-08,2017-11-11,Second Class,Consumer,Henderson,Kentucky,South,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",500.558
2,2017-06-12,2017-06-16,Second Class,Corporate,Los Angeles,California,West,Office Supplies,Labels,Self-Adhesive Address Labels For Typewriters B...,14.620
3,2016-10-11,2016-10-18,Standard Class,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,Bretford Cr4500 Series Slim Rectangular Table,500.558
4,2016-10-11,2016-10-18,Standard Class,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.368

In [59]:
# Convert the 'Sales' column values to integers for consistency in numerical operations
df['Sales'] = df['Sales'].astype(int)

In [60]:
# Convert 'Order_Date' and 'Ship_Date' columns from string/object format to DateTime format
# This allows easy extraction of date-related information and facilitates time-based analysis
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'])

In [61]:
# Extract the year, month, and weekday from 'Ship_Date' to create new columns
df['year_ship_date'] = df['Ship_Date'].dt.year  # Extracts the year (e.g., 2023)
df['month_ship_date'] = df['Ship_Date'].dt.month  # Extracts the month (1-12)
df['weekday_ship_date'] = df['Ship_Date'].dt.weekday  # Extracts the weekday (0 = Monday, 6 = Sunday)

In [62]:
# Extract the year, month, and weekday from 'Order_Date' to create new columns
df['year_order_date'] = df['Order_Date'].dt.year  # Extracts the year (e.g., 2023)
df['month_order_date'] = df['Order_Date'].dt.month  # Extracts the month (1-12)
df['weekday_order_date'] = df['Order_Date'].dt.weekday  # Extracts the weekday (0 = Monday, 6 = Sunday)

In [63]:
nc = df.select_dtypes(include=[np.number]) # Use the np alias to access the number type
c_matrix = nc.corr()
c_matrix # Printing Corelation matrix

,Sales,year_ship_date,month_ship_date,weekday_ship_date,year_order_date,month_order_date,weekday_order_date
Sales,1.000000,-0.019105,0.019082,-0.000935,-0.017755,0.013073,-0.002561
year_ship_date,-0.019105,1.000000,-0.032789,-0.036412,0.994090,-0.001222,0.041617
month_ship_date,0.019082,-0.032789,1.000000,-0.007191,-0.005500,0.911744,0.022459
weekday_ship_date,-0.000935,-0.036412,-0.007191,1.000000,-0.033424,-0.022108,-0.111963
year_order_date,-0.017755,0.994090,-0.005500,-0.033424,1.000000,-0.018463,0.039060
month_order_date,0.013073,-0.001222,0.911744,-0.022108,-0.018463,1.000000,0.035323
weekday_order_date,-0.002561,0.041617,0.022459,-0.111963,0.039060,0.035323,1.000000

In [64]:
# Saving the cleaned dataset
df.to_csv("cleaned.csv", index=False)